language: php

sudo: false

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/php-cs-fixer fix src --dry-run
  - ./vendor/bin/phpstan analyse --configuration=phpstan.neon
  - ./vendor/bin/phpunit
